<template>
  <div class="flex justify-center">
    <div class="pb-8 prose">
      <center><h1>Privacy Policy</h1></center>

      <p><strong>Last updated:</strong> July 6th, 2023</p>

      <p>
        Welcome to Catetry.com. This Privacy Policy outlines how we collect,
        use, and disclose information through the Website. Please read this
        policy carefully to understand our practices regarding your information.
      </p>

      <p>
        Your privacy is important to us. It is Spero Autem LLCs&#39; policy to
        respect your privacy and comply with any applicable law and regulation
        regarding any personal information we may collect about you, including
        across our website,
        <a href="https://catetry.com">Catetry.com</a>, and other sites we own
        and operate.
      </p>

      <h2>Information We Collect</h2>

      <ul>
        <li>
          <strong>Information about Your Cat:</strong> We may collect
          information that you provide about your cat including its name, breed,
          and attributes.
        </li>
        <li>
          <strong>Generated Poems:</strong> We store poems that are generated
          through the use of ChatGPT 3.5.
        </li>
        <li>
          <strong>Cookies and Similar Technologies:</strong> We use cookies and
          similar technologies to analyze user behavior and improve the
          functionality of our Website. Google Analytics is used to analyze
          traffic and user interaction with the Website.
        </li>
        <!--<li>
          <strong>Third-Party Advertising:</strong> We use Google Ads to display
          advertisements. Google may use cookies to serve ads based on a user’s
          prior visits to your website or other websites.
        </li>-->
      </ul>

      <h2>How We Use the Information</h2>

      <p>We use the information collected for the following purposes:</p>

      <ul>
        <li>To provide and maintain the Website.</li>
        <li>To improve and personalize your experience on our Website.</li>
        <li>
          To monitor and analyze usage and trends to improve the functionality
          and user experience of the Website.
        </li>
        <li>To serve relevant advertisements.</li>
      </ul>

      <h2>Third-Party Services</h2>

      <p>
        We may use third-party services such as Google Analytics and Google Ads.
        These third-party services may collect information sent by your browser
        as part of a web page request, such as cookies or your IP address.
      </p>

      <ul>
        <li>
          <strong>Google Analytics:</strong> Our Website uses Google Analytics,
          a web analytics service provided by Google, Inc. The information
          generated by the cookie about your use of our Website (including your
          IP address) will be transmitted to and stored by Google on servers in
          the United States. For more information on Google's privacy practices,
          please see
          <a
            href="https://policies.google.com/privacy"
            target="_blank"
            rel="noopener"
            >Google's Privacy Policy</a
          >.
        </li>
        <!--<li>
          <strong>Google Ads:</strong> Our Website uses Google Ads for
          advertising. Google Ads uses cookies to serve ads based on your prior
          visits to our Website. For more information on how Google Ads uses
          data, please see
          <a
            href="https://policies.google.com/technologies/ads"
            target="_blank"
            rel="noopener"
            >Google’s Advertising Privacy Policy</a
          >.
        </li>-->
      </ul>

      <h2>How You Can Control Cookies</h2>

      <p>
        Most web browsers allow you to control cookies through their settings
        preferences. However, if you limit the ability of websites to set
        cookies, you may worsen your overall user experience.
      </p>

      <h2>Changes to this Privacy Policy</h2>

      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page and
        updating the “Last Updated” date at the top of this Privacy Policy. You
        are advised to review this Privacy Policy periodically for any changes.
      </p>

      <h2>Contact Us</h2>

      <p>
        If you have any questions about this Privacy Policy, please contact us
        at Spero Autem USA # +1 267-753-9235.
      </p>
    </div>
  </div>
</template>

<script lang="ts" setup>
useHead({
  title: "Privacy Policy",
  meta: [
    {
      name: "description",
      content:
        "Your privacy is important to us. It is Catetrys&#39; policy to respect your privacy and comply with any applicable law and regulation regarding any personal information we may collect about you.",
    },
  ],
});
</script>